services:
  - type: web
    name: lmx-content-training-assistant
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: APP_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
